<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Model Comparison – camdl</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js" integrity="sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2" crossorigin="anonymous"></script><script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../inference/likelihood.html" rel="next">
<link href="../../guide/fitting-data/report.html" rel="prev">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-7f8f88aac4f3542376d5c11b86a4c14d.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-dark-d0ae9245876894da5ac7e18953ecc5cc.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-7f8f88aac4f3542376d5c11b86a4c14d.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-b981944dac36b7fff9ce3ceeec90f8de.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../../site_libs/bootstrap/bootstrap-dark-73b7f00512812729446172a063b47ee0.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="../../site_libs/bootstrap/bootstrap-b981944dac36b7fff9ce3ceeec90f8de.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js" integrity="sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../guide/getting-started.html">Getting Started</a></li><li class="breadcrumb-item"><a href="../../guide/fitting-data/model_comparison.html"><span class="chapter-title">Model Comparison</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../../">camdl</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/vsbuffalo/camdl-book" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../index.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">What is camdl?</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Getting Started</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../guide/getting-started.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Building an SIR Model</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../guide/experiments.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Uncertainty, Priors, and Simulation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../guide/scenarios.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Scenarios, Interventions, and Sweeps</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../guide/dimensions.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Dimensions and Stratification</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../guide/fitting-data/report.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Fitting to Data</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../guide/fitting-data/model_comparison.html" class="sidebar-item-text sidebar-link active"><span class="chapter-title">Model Comparison</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Inference</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../inference/likelihood.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Likelihood and the Particle Filter</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../inference/algorithms.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Algorithms: IF2, PGAS, and PMMH</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Vignettes</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Reference</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../language/spec.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Language Specification</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../language/data-spec.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Data Model</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../reference/features.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">User Features</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../reference/inference-spec.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Inference Specification</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../reference/ir-spec.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">IR Specification</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../reference/runtimes.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Simulation Backends</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../reference/design.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Design Philosophy</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#what-well-compute-and-why" id="toc-what-well-compute-and-why" class="nav-link active" data-scroll-target="#what-well-compute-and-why">What we’ll compute and why</a></li>
  <li><a href="#aic-and-bic-the-textbook-answer" id="toc-aic-and-bic-the-textbook-answer" class="nav-link" data-scroll-target="#aic-and-bic-the-textbook-answer">AIC and BIC — the textbook answer</a></li>
  <li><a href="#windowed-holdout-and-why-one-cut-isnt-enough" id="toc-windowed-holdout-and-why-one-cut-isnt-enough" class="nav-link" data-scroll-target="#windowed-holdout-and-why-one-cut-isnt-enough">Windowed holdout — and why one cut isn’t enough</a></li>
  <li><a href="#prequential-scoring-dawids-decomposition" id="toc-prequential-scoring-dawids-decomposition" class="nav-link" data-scroll-target="#prequential-scoring-dawids-decomposition">Prequential scoring — Dawid’s decomposition</a>
  <ul class="collapse">
  <li><a href="#step-1-record-a-prequential-trace-for-each-model" id="toc-step-1-record-a-prequential-trace-for-each-model" class="nav-link" data-scroll-target="#step-1-record-a-prequential-trace-for-each-model">Step 1 — record a prequential trace for each model</a></li>
  <li><a href="#step-2-the-model-comparison-table" id="toc-step-2-the-model-comparison-table" class="nav-link" data-scroll-target="#step-2-the-model-comparison-table">Step 2 — the model-comparison table</a></li>
  <li><a href="#step-3-the-per-day-story-python-reading-the-json-traces" id="toc-step-3-the-per-day-story-python-reading-the-json-traces" class="nav-link" data-scroll-target="#step-3-the-per-day-story-python-reading-the-json-traces">Step 3 — the per-day story (Python reading the JSON traces)</a></li>
  </ul></li>
  <li><a href="#a-deliberate-caveat-about-t_0" id="toc-a-deliberate-caveat-about-t_0" class="nav-link" data-scroll-target="#a-deliberate-caveat-about-t_0">A deliberate caveat about <span class="math inline">\(t_0\)</span></a></li>
  <li><a href="#the-final-converging-answer" id="toc-the-final-converging-answer" class="nav-link" data-scroll-target="#the-final-converging-answer">The final converging answer</a></li>
  <li><a href="#what-camdls-v1-prequential-release-makes-easy-vs-hard" id="toc-what-camdls-v1-prequential-release-makes-easy-vs-hard" class="nav-link" data-scroll-target="#what-camdls-v1-prequential-release-makes-easy-vs-hard">What camdl’s v1 prequential release makes easy vs hard</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/vsbuffalo/camdl-book/edit/main/guide/fitting-data/model_comparison.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">


<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../guide/getting-started.html">Getting Started</a></li><li class="breadcrumb-item"><a href="../../guide/fitting-data/model_comparison.html"><span class="chapter-title">Model Comparison</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-title">Model Comparison</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>This chapter compares three observation / process-noise models for the 1978 boarding-school influenza outbreak. It uses <code>camdl</code>‘s v1 prequential-evaluation framework end-to-end: <code>camdl pfilter --save-prequential</code> to record one-step-ahead predictive traces for each model’s MLE, then <code>camdl compare</code> to produce the publication table. No Python glue for the model-comparison table itself — the tool ships the mechanism. We add Python only for one time-resolved diagnostic plot that reads the traces’ JSON directly.</p>
<p>The three candidates, all built on the same chain-binomial SIR:</p>
<ol type="1">
<li><strong>Poisson observation</strong> — <span class="math inline">\(y_t \sim \text{Poisson}(I_t)\)</span>. Two estimated parameters, <span class="math inline">\(\beta\)</span> and <span class="math inline">\(\gamma\)</span>.</li>
<li><strong>Negative-binomial observation</strong> — <span class="math inline">\(y_t \sim \text{NegBin}(I_t, k)\)</span>. Three parameters; <span class="math inline">\(k\)</span> widens observation error.</li>
<li><strong>Poisson observation + process noise on <span class="math inline">\(\beta\)</span></strong> — using camdl’s <code>overdispersed(rate, sigma_se)</code> primitive (He, Ionides &amp; King 2010). Three parameters; extra variance lives in the dynamics, not in the counting.</li>
</ol>
<section id="what-well-compute-and-why" class="level2">
<h2 class="anchored" data-anchor-id="what-well-compute-and-why">What we’ll compute and why</h2>
<p>The goal is to say <em>which story the data prefers</em> — and mean it. Three questions in sequence:</p>
<ul>
<li><strong>Does penalised in-sample likelihood (AIC/BIC) suffice?</strong> No, and the failure is instructive.</li>
<li><strong>Does a single train/test split suffice?</strong> Also no, and the failure has a different cause.</li>
<li><strong>Does prequential scoring with a proper scoring rule succeed?</strong> Yes, with diagnostics we can actually read.</li>
</ul>
</section>
<section id="aic-and-bic-the-textbook-answer" class="level2">
<h2 class="anchored" data-anchor-id="aic-and-bic-the-textbook-answer">AIC and BIC — the textbook answer</h2>
<table class="caption-top table">
<thead>
<tr class="header">
<th>model</th>
<th>k</th>
<th>log-lik</th>
<th>AIC</th>
<th>BIC</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Poisson</td>
<td>2</td>
<td>-61.14</td>
<td>126.28</td>
<td>127.56</td>
</tr>
<tr class="even">
<td>NegBin</td>
<td>3</td>
<td>-58.09</td>
<td>122.18</td>
<td>124.10</td>
</tr>
<tr class="odd">
<td>Procnoise</td>
<td>3</td>
<td>-56.39</td>
<td><strong>118.78</strong></td>
<td><strong>120.70</strong></td>
</tr>
</tbody>
</table>
<p>AIC and BIC both pick procnoise on the full-data fits, but they only see <strong>in-sample</strong> fit; they cannot detect overfitting. The failure mode we’ll now demonstrate: a model that overfits training data will win on AIC/BIC at some holdout cuts while losing badly out-of-sample.</p>
</section>
<section id="windowed-holdout-and-why-one-cut-isnt-enough" class="level2">
<h2 class="anchored" data-anchor-id="windowed-holdout-and-why-one-cut-isnt-enough">Windowed holdout — and why one cut isn’t enough</h2>
<p>Fit on days 0–7, score on days 8–13:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>model</th>
<th>k</th>
<th>train ll (n=8)</th>
<th>train AIC</th>
<th><strong>holdout ll (n=6)</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Poisson</td>
<td>2</td>
<td>-35.83</td>
<td>75.66</td>
<td><strong>-22.66</strong></td>
</tr>
<tr class="even">
<td>NegBin</td>
<td>3</td>
<td>-32.95</td>
<td>71.90</td>
<td><strong>-24.80</strong></td>
</tr>
<tr class="odd">
<td>Procnoise</td>
<td>3</td>
<td>-33.35</td>
<td>72.70</td>
<td><strong>-22.41</strong></td>
</tr>
</tbody>
</table>
<p><strong>Train AIC picks NegBin; holdout ll picks procnoise, and NegBin finishes <em>last</em>.</strong> NegBin overfits the training noise and generalizes worst.</p>
<p>Repeat with the cut at day 3 (train on days 0–3, holdout 4–13):</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>model</th>
<th>k</th>
<th>train ll (n=4)</th>
<th><strong>holdout ll (n=10)</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Poisson</td>
<td>2</td>
<td>-11.98</td>
<td><strong>-108.89</strong></td>
</tr>
<tr class="even">
<td>NegBin</td>
<td>3</td>
<td>-11.94</td>
<td><strong>-54.66</strong></td>
</tr>
<tr class="odd">
<td>Procnoise</td>
<td>3</td>
<td>-12.14</td>
<td><strong>-81.65</strong></td>
</tr>
</tbody>
</table>
<p>Now <strong>NegBin wins by 27 nats</strong> — but only because four training points don’t identify <span class="math inline">\((\beta, \gamma)\)</span>, and the three models’ MLEs land at different points on an essentially flat likelihood surface. Train ll’s agree to within 0.2 nats; the 54-nat holdout gap is dictated by which lucky <span class="math inline">\(\gamma\)</span> each model happened to settle on.</p>
<p>Two holdout cuts, two rankings. A single scalar from a single split cannot tell you that the result is artefact-dominated. This is why we want a principled, symmetric, time-respecting score.</p>
<p>See <code>figures/holdout_comparison.png</code> and <code>figures/holdout_rising_comparison.png</code> for the bar-chart versions of both experiments.</p>
</section>
<section id="prequential-scoring-dawids-decomposition" class="level2">
<h2 class="anchored" data-anchor-id="prequential-scoring-dawids-decomposition">Prequential scoring — Dawid’s decomposition</h2>
<p>For observations <span class="math inline">\(y_{1:T}\)</span>, the joint log-likelihood factorizes as</p>
<p><span class="math display">\[
\log p(y_{1:T}) \;=\; \sum_{t=0}^{T-1} \log p(y_{t+1} \mid y_{1:t}).
\]</span></p>
<p>Each term is a forecast made using only the past (Dawid 1984). For a state-space model at plug-in MLE <span class="math inline">\(\hat\theta\)</span>, the bootstrap particle filter computes these terms by construction — the “incremental log-likelihood” at each assimilation step is exactly <span class="math inline">\(\log \hat p(y_{t+1} \mid y_{1:t}, \hat\theta)\)</span>. So prequential scoring is essentially free: one <code>pfilter</code> run per model, no refitting.</p>
<p>As of v1 (<code>camdl</code> ≥ 0.1.0+e53046a) this pipeline is first-class. <code>camdl pfilter --save-prequential NAME</code> records the trace at <code>NAME.json</code> (full typed trace with per-particle predictive samples) and <code>NAME.tsv</code> (scalar per-step scores). <code>camdl compare</code> reads those JSON files and emits the publication table.</p>
<section id="step-1-record-a-prequential-trace-for-each-model" class="level3">
<h3 class="anchored" data-anchor-id="step-1-record-a-prequential-trace-for-each-model">Step 1 — record a prequential trace for each model</h3>
<details class="cli-run"><summary><code>$ camdl pfilter boarding_school_sir.ir.json --params &lt;poisson MLE&gt; --data data/in_bed.tsv --particles 5000 --seed 1 --save-prequential preq/poisson</code></summary><pre class="ansi-output"><code>-62.5158
<span style="opacity:0.7">pfilter: 14 observations, 5000 particles, dt=1, seed=1
pfilter: obs_model=in_bed, likelihood=poisson
prequential trace written: elpd=-62.52, mean_crps=14.281, PIT 90% cov=0.71</span></code></pre></details>
<details class="cli-run"><summary><code>$ camdl pfilter boarding_school_sir_negbin.ir.json --params &lt;negbin MLE&gt; --data data/in_bed.tsv --particles 5000 --seed 1 --save-prequential preq/negbin</code></summary><pre class="ansi-output"><code>-58.4465
<span style="opacity:0.7">pfilter: 14 observations, 5000 particles, dt=1, seed=1
pfilter: obs_model=in_bed, likelihood=neg_binomial
prequential trace written: elpd=-58.45, mean_crps=13.990, PIT 90% cov=0.79</span></code></pre></details>
<details class="cli-run"><summary><code>$ camdl pfilter boarding_school_sir_procnoise.ir.json --params &lt;procnoise profile MLE&gt; --data data/in_bed.tsv --particles 5000 --seed 1 --save-prequential preq/procnoise</code></summary><pre class="ansi-output"><code>-56.5137
<span style="opacity:0.7">pfilter: 14 observations, 5000 particles, dt=1, seed=1
pfilter: obs_model=in_bed, likelihood=poisson
prequential trace written: elpd=-56.51, mean_crps=12.874, PIT 90% cov=0.86</span></code></pre></details>
<p>Each invocation reports the total elpd, mean CRPS, and PIT 90% coverage as a sanity line. The TSV is per-step scalars (<code>t, y_obs, log_score, crps, pit, ess</code>); the JSON contains the full typed trace including per-particle predictive samples at each step.</p>
</section>
<section id="step-2-the-model-comparison-table" class="level3">
<h3 class="anchored" data-anchor-id="step-2-the-model-comparison-table">Step 2 — the model-comparison table</h3>
<details class="cli-run"><summary><code>$ camdl compare preq/poisson.json preq/negbin.json preq/procnoise.json</code></summary><pre class="ansi-output"><code>Model            T_score     elpd   Δelpd     E_T   se(Δ)     crps    Δcrps   PIT_cov90
───────────────────────────────────────────────────────────────────────────────────────
poisson.json          14   -62.52   -6.00   0.002    5.93   14.281   +1.407        0.71
negbin.json           14   -58.45   -1.93   0.145    2.83   13.990   +1.116        0.79
procnoise.json        14   -56.51       —       —       —   12.874        —        0.86

Scored steps: 14 (t0=0).  Baseline: procnoise.json.</code></pre></details>
<p>That’s the tool doing the work, unmediated. <code>T_score = 14</code> matches across all three models (no <span class="math inline">\(t_0\)</span> burn-in here; see the caveat below).</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Column definitions
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ul>
<li><strong>model</strong>: label derived from the JSON filename.</li>
<li><strong>T_score</strong>: number of scored time steps (observation windows). Must match across models for a fair comparison — the tool refuses if they differ (override: <code>--allow-mismatched-horizon</code>).</li>
<li><strong>elpd</strong>: expected log pointwise predictive density — the sum of one-step-ahead log predictive scores across all <span class="math inline">\(T\)</span> steps. Higher (less negative) is better. This is the prequential analogue of leave-one-out cross-validation: each step is predicted using only past data, so elpd rewards models that generalize, not just fit.</li>
<li><strong>Δelpd</strong>: difference in elpd from the baseline model (auto-selected as the highest-elpd model, marked <code>[baseline]</code>). Negative means worse than baseline.</li>
<li><strong>E_T</strong>: the e-value — <code>exp(Δelpd)</code>, interpretable as the final wealth of a $1 bettor wagering on this model against the baseline at each time step. <code>E_T = 0.002</code> means the baseline is overwhelmingly favored (equivalently, betting <em>on</em> the baseline against this model yields $1/0.002 = $500). <code>E_T</code> near 1 means the models are indistinguishable. Unlike se(Δ), the e-value doesn’t rely on a CLT approximation over <span class="math inline">\(T\)</span> steps, so it remains valid for short series.</li>
<li><strong>se(Δ)</strong>: standard error of Δelpd, computed as the standard error of the <em>paired</em> per-step log-score differences. A |Δ| &lt; 2 × se(Δ) means the difference is within sampling noise — the models are indistinguishable on this data.</li>
<li><strong>crps</strong>: mean Continuous Ranked Probability Score across steps. Lower is better. CRPS is in the same units as the observations (here: boys in bed per day), making it directly interpretable. It is also more robust than log score to outlier steps.</li>
<li><strong>PIT_90</strong>: proportion of observations falling within the model’s central 90% predictive interval (probability integral transform coverage). Nominal is 0.90 — values well below indicate overconfidence (intervals too narrow); values above indicate overdispersion.</li>
</ul>
</div>
</div>
</div>
<p><strong>Reading the table:</strong></p>
<ul>
<li><strong>Procnoise wins on elpd</strong> by ~2 nats over NegBin, ~6 over Poisson. Poisson’s <code>se(Δ) = 5.93</code> is huge because one day dominates the difference (see §Step 3).</li>
<li><strong>The E_T column makes this concrete.</strong> Poisson’s <code>E_T = 0.002</code> means a bettor wagering on procnoise against Poisson would turn $1 into ~$400 over the 14 observation days. NegBin’s <code>E_T = 0.145</code> is moderate — the evidence favors procnoise but isn’t overwhelming in just 14 steps.</li>
<li><strong>Mean CRPS is in units of observations</strong> (boys in bed): procnoise is 1.1–1.3 boys/day better than the competitors, which is interpretable in a way log-lik is not.</li>
<li><strong>PIT coverage</strong> tells you the models are roughly well-calibrated at the 90% level (0.71 / 0.79 / 0.86; nominal 0.90). Poisson is the most overconfident, consistent with its tight-observation-likelihood assumption.</li>
</ul>
<p><strong>Same table via <code>--format md</code></strong> — the command’s stdout is markdown source (drop it directly into a paper); the rendered version is shown below:</p>
<div class="cli-run-md"><code>$ camdl compare preq/*.json --format md</code></div>
<table class="caption-top table">
<colgroup>
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
</colgroup>
<thead>
<tr class="header">
<th>Model</th>
<th>T_score</th>
<th>elpd</th>
<th>Δelpd</th>
<th>E_T</th>
<th>se(Δ)</th>
<th>crps</th>
<th>Δcrps</th>
<th>PIT_cov90</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>poisson.json</td>
<td>14</td>
<td>-62.52</td>
<td>-6.00</td>
<td>0.002</td>
<td>5.93</td>
<td>14.281</td>
<td>+1.407</td>
<td>0.71</td>
</tr>
<tr class="even">
<td>negbin.json</td>
<td>14</td>
<td>-58.45</td>
<td>-1.93</td>
<td>0.145</td>
<td>2.83</td>
<td>13.990</td>
<td>+1.116</td>
<td>0.79</td>
</tr>
<tr class="odd">
<td>procnoise.json</td>
<td>14</td>
<td>-56.51</td>
<td>—</td>
<td>—</td>
<td>—</td>
<td>12.874</td>
<td>—</td>
<td>0.86</td>
</tr>
</tbody>
</table>
<p><strong>And the JSON</strong>, which is the plotting contract:</p>
<details class="cli-run"><summary><code>$ camdl compare preq/*.json --format json</code></summary><pre class="ansi-output"><code>{
  "baseline": "procnoise.json",
  "metrics": [
    "elpd",
    "crps",
    "pit_cov90"
  ],
  "rows": [
    {
      "delta_elpd": -6.002097677884706,
      "delta_mean_crps": 1.4067798457142848,
      "e_t": 0.002473558002800163,
      "elpd": -62.51577423595041,
      "mean_crps": 14.280848674285718,
      "name": "poisson.json",
      "path": "test_procnoise/preq/poisson.json",
      "pit_cov90": 0.7142857142857143,
      "se_delta_elpd": 5.929324868053064,
  [...22 lines omitted...]
      "pit_cov90": 0.8571428571428571,
      "se_delta_elpd": null,
      "t_score": 14
    }
  ]
}</code></pre></details>
</section>
<section id="step-3-the-per-day-story-python-reading-the-json-traces" class="level3">
<h3 class="anchored" data-anchor-id="step-3-the-per-day-story-python-reading-the-json-traces">Step 3 — the per-day story (Python reading the JSON traces)</h3>
<p>The compare table gives scalars; the per-step structure tells us <em>where</em> the models differentiate. This is the one part that stays in Python because it’s presentation, not computation. The JSON traces have everything we need.</p>
<div id="fig-preq" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-preq-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figures/preq_comparison.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-preq-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;7.1: Prequential comparison rendered from the three JSON traces. Top-row middle: per-day log score — day 4 (the outbreak’s acceleration) dominates the Δelpd between models. Top-row right: PF effective sample size per step — Poisson’s collapses to ~20 on day 4, a direct indicator of model mis-specification. Bottom-left: cumulative prequential log-lik over time, whose final heights equal the bar-chart on the bottom-right.
</figcaption>
</figure>
</div>
<p><strong>What the figure adds that the <code>compare</code> table can’t:</strong> day 4 — the outbreak’s acceleration from 76 to 225 cases — carries essentially all the model-discrimination. Other days score within ~0.3 nats across models. Poisson’s PF collapses to ESS ≈ 20 on day 4 (99.6% depletion), a mechanical warning that the data has moved somewhere Poisson’s state space does not want to be. NegBin widens the obs error enough to survive; procnoise lets the trajectory itself jitter via <span class="math inline">\(\sigma_{se}\)</span> and assigns the observed acceleration real probability mass without needing cartoonish observation bars.</p>
</section>
</section>
<section id="a-deliberate-caveat-about-t_0" class="level2">
<h2 class="anchored" data-anchor-id="a-deliberate-caveat-about-t_0">A deliberate caveat about <span class="math inline">\(t_0\)</span></h2>
<p>The comparison above has <span class="math inline">\(t_0 = 0\)</span> — every day is scored, including the first few where the filter is still seeded by the prior. The v1 proposal (<a href="prequential-proposal.md#71-api-surface">§7.1</a>) defaults <span class="math inline">\(t_0\)</span> to a model-structure heuristic with a warning, and offers <code>--compute-t0-threshold</code> as an opt-in identifiability sweep.</p>
<p>For this chapter’s comparison we deliberately score from <span class="math inline">\(t=0\)</span> because: - The three models share identical priors and initial conditions, so prior-dominated early scores are the <em>same</em> across models and don’t bias Δelpd. - PF effective sample size is high at <span class="math inline">\(t=0\)</span> across all three (5000 by definition), so Monte-Carlo noise isn’t amplified. - In the worked example of the v1 proposal (<span class="math inline">\(t_0 = 5\)</span>), the ranking is the same; scoring from <span class="math inline">\(t=0\)</span> here gives the reader more per-day structure to look at.</p>
<p>For a publication comparison, the right move is <code>--compute-t0-threshold</code> — that’s the Tier-1 discipline, where a user-supplied <span class="math inline">\(t_0\)</span> below the computed identifiability threshold errors. v1 warns; v2 makes the sweep default once incremental-IF2 caching lands.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Why two scoring columns — and why the tool doesn’t combine them
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The table reports both elpd (log score) and mean CRPS because they measure different things and <code>camdl compare</code> refuses to combine them into a single headline ranking.</p>
<p><strong>Log score</strong> rewards predictive density concentrated at the observed point. It has a multiplicative structure: differences in elpd are log-likelihood-ratios, so <code>exp(Δelpd)</code> is the e-value / Bayes factor (the E_T column). This is what makes the testing-by-betting interpretation, Bayesian updating, and the “nats of evidence” scale coherent. Log score is measured in nats.</p>
<p><strong>CRPS</strong> rewards calibrated CDFs overall — it integrates the squared difference between the predictive CDF and the empirical CDF across all thresholds. It is measured in the units of the observations (here: boys in bed per day). CRPS has no ratio interpretation: <code>exp(ΔCRPS)</code> is not a likelihood ratio, not a probability, not an e-value — it’s meaningless.</p>
<p>Because they live in different units (nats vs.&nbsp;cases/day), any combined ranking would require an exchange rate — equal-weight z-scoring, rank aggregation, or similar — and that is a methodological choice, not a measurement. The tool does not make that choice on your behalf.</p>
<p><strong>When they agree,</strong> the ranking is robust. <strong>When they disagree,</strong> the disagreement is itself diagnostic: typically the log-score winner has a sharper predictive that is well-calibrated at the observed points, while the CRPS winner is more diffuse but covers tails better.</p>
<p><strong>Which metric you trust more depends on what you’ll do with the model.</strong> If the model feeds a Bayesian decision pipeline — posterior parameter estimates, likelihood-ratio tests, evidence synthesis — then log score is the natural loss, because it directly measures the quality of the predictive density that those downstream methods consume. If the model produces interval forecasts for operational use — epidemic thresholds, resource planning, forecasting hub submissions — then CRPS matters more, because it evaluates the full predictive CDF that generates those intervals. The scoring rule should match the loss function of the decision the model is serving. Different proper scoring rules correspond to different loss functions (Gneiting 2011, “Making and evaluating point forecasts,” <em>JASA</em>); aggregating them requires a decision-theoretic commitment that belongs to the analyst, not the tool.</p>
<p>On this dataset, elpd and CRPS agree: procnoise wins both. That agreement is the strong version of the result.</p>
</div>
</div>
</div>
</section>
<section id="the-final-converging-answer" class="level2">
<h2 class="anchored" data-anchor-id="the-final-converging-answer">The final converging answer</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>metric</th>
<th>Poisson</th>
<th>NegBin</th>
<th>Procnoise</th>
<th>winner</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>full-data AIC</td>
<td>126.28</td>
<td>122.18</td>
<td><strong>118.78</strong></td>
<td>Procnoise</td>
</tr>
<tr class="even">
<td>full-data BIC</td>
<td>127.56</td>
<td>124.09</td>
<td><strong>120.70</strong></td>
<td>Procnoise</td>
</tr>
<tr class="odd">
<td>falling-edge holdout ll</td>
<td><span class="math inline">\(-58.49\)</span></td>
<td><span class="math inline">\(-57.75\)</span></td>
<td><strong><span class="math inline">\(-55.76\)</span></strong></td>
<td>Procnoise</td>
</tr>
<tr class="even">
<td><strong>prequential elpd</strong> (camdl compare)</td>
<td><span class="math inline">\(-62.44\)</span></td>
<td><span class="math inline">\(-58.42\)</span></td>
<td><strong><span class="math inline">\(-56.47\)</span></strong></td>
<td>Procnoise</td>
</tr>
<tr class="odd">
<td>prequential mean CRPS</td>
<td>14.15</td>
<td>13.95</td>
<td><strong>12.83</strong></td>
<td>Procnoise</td>
</tr>
<tr class="even">
<td>PIT 90% coverage</td>
<td>0.71</td>
<td>0.79</td>
<td><strong>0.86</strong></td>
<td>Procnoise (closest to nominal 0.90)</td>
</tr>
</tbody>
</table>
<p>Four metrics, four rankings, one answer. <strong>Process noise on <span class="math inline">\(\beta\)</span> is a better model than either Poisson or NegBin observation dispersion on this dataset.</strong> The margin is modest (~2 nats prequential elpd over NegBin), but it is consistent across in-sample, out-of-sample, and time-resolved metrics, and it tells a mechanistically coherent story: the extra variance lives in the dynamics, not in the counting.</p>
</section>
<section id="what-camdls-v1-prequential-release-makes-easy-vs-hard" class="level2">
<h2 class="anchored" data-anchor-id="what-camdls-v1-prequential-release-makes-easy-vs-hard">What camdl’s v1 prequential release makes easy vs hard</h2>
<p><strong>Easy now:</strong></p>
<ul>
<li>One <code>pfilter</code> call per model produces the full typed prequential trace, including per-particle predictive samples.</li>
<li><code>camdl compare</code> renders the publication table. Baseline auto-selection by best elpd; paired-per-step Δelpd SE; mean CRPS as a robust complement; PIT 90% coverage inline as an overconfidence flag; markdown and JSON output for paper drafts and downstream plotting.</li>
<li>Structural-fairness preflight refuses when <code>T_score</code> mismatches across models (override: <code>--allow-mismatched-horizon</code>).</li>
</ul>
<p><strong>Harder / not yet in v1</strong> (see Part II of the proposal):</p>
<ul>
<li>Full LFO-PSIS for PMMH / PGAS posteriors (we’re plug-in only here).</li>
<li>Pseudo-posterior from IF2 chain cloud (we did manual <span class="math inline">\(\sigma_{se}\)</span> profiling instead).</li>
<li>Randomized PIT for count data (we use point-estimate PIT).</li>
<li>E-process / betting display mode, with a one-line interpretation disclaimer.</li>
<li>Anti-pattern detection (<span class="math inline">\(t_0 = 0\)</span> warning, seed-collision refusal).</li>
<li>Identifiability-sweep-derived <span class="math inline">\(t_0\)</span> default (we used <span class="math inline">\(t_0=0\)</span> and justified it above; Tier-1 would have checked it).</li>
</ul>
</section>
<section id="references" class="level2">
<h2 class="anchored" data-anchor-id="references">References</h2>
<ul>
<li><strong>Dawid, A.P. (1984).</strong> “Statistical theory: The prequential approach.” <em>JRSS-A</em> 147(2): 278–292.</li>
<li><strong>Gneiting, T. &amp; Raftery, A.E. (2007).</strong> “Strictly proper scoring rules, prediction, and estimation.” <em>JASA</em> 102(477): 359–378.</li>
<li><strong>Bürkner, P.-C., Gabry, J. &amp; Vehtari, A. (2020).</strong> “Approximate leave-future- out cross-validation for Bayesian time series models.” <em>J. Stat. Comput. Simul.</em> 90: 2499–2523.</li>
<li><strong>He, D., Ionides, E.L. &amp; King, A.A. (2010).</strong> “Plug-and-play inference for disease dynamics.” <em>J. R. Soc. Interface</em> 7: 271–283.</li>
<li><strong>King, A.A., Nguyen, D. &amp; Ionides, E.L. (2016).</strong> “Statistical inference for partially observed Markov processes via the R package pomp.” <em>JSS</em> 69: 1–43.</li>
<li><strong>camdl prequential-evaluation proposal</strong> (<code>docs/dev/proposals/2026-04-20-prequential-evaluation.md</code>) — this chapter uses Part I (“v1 scope”); Part II items are flagged where relevant.</li>
</ul>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../../guide/fitting-data/report.html" class="pagination-link" aria-label="Fitting to Data">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-title">Fitting to Data</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../../inference/likelihood.html" class="pagination-link" aria-label="Likelihood and the Particle Filter">
        <span class="nav-page-text"><span class="chapter-title">Likelihood and the Particle Filter</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>© 2026 Vince Buffalo. Supported by the Institute for Disease Modeling, Bill &amp; Melinda Gates Foundation.</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    <div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/vsbuffalo/camdl-book/edit/main/guide/fitting-data/model_comparison.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li></ul></div></div>
    <div class="nav-footer-right">
<p>License: <a href="https://creativecommons.org/licenses/by/4.0/">CC BY 4.0</a></p>
</div>
  </div>
</footer>
<script src="cli-copy.js"></script>




</body></html>